export const endpointsConfig = {
    administration: {
        getAllUsersInfo: "/get-all-users-info",
        baseUrl: "/administration",
    },
    authentication: {
        baseUrl: "/authentication",
        registration: "/registration",
        loginByEmail: "/login/by/email",
        loginByUsername: "/login/by/username",
        checkUsernameAvailability: "/check-username-availability/:username",
        checkSession: "/check-session",
        logout: "/logout",
    },
    userAccount: {
        baseUrl: "/user-account",
        exploreMe: "/explore/my-account",
        setEmail: "/set/email",
        updateEmail: "/update/email",
        updatePassword: "/update/password",
        updateUsername: "/update/username-to/:username",
        allSessions: "/get/all-sessions",
        terminateOtherSessions: "/sessions/terminate-other-sessions",
        terminateSpecificSession: "/sessions/terminate-specific-session/:session_id",
        deleteAccount: "/delete-account",
    },
    userProfile: {
        baseUrl: "/user-profile",
        exploreOthersProfile: "/explore/others-profile/:username",
        viewMyProfile: "/view/my-profile",
        updateBio: "/update/bio",
        updateNickname: "/update/nickname/to/:nickname",
    },
    commentAboutAnime: {
        baseUrl: "/comment-about-anime",
        allCommentsForAnime: "/get/all-comments-for-anime/:anime_id",
        getAllMyComments: "/get/all-my-comments",
        getAllCommentsFromAnyProfile: "/get/all-for-public-profile/:username",
        createComment: "/create/:anime_id",
        updateComment: "/update/:comment_id",
        deleteComment: "/delete/:comment_id",
        reportTheComment: "/report-the-comment",
        addLike: "/add/like/:comment_id",
        deleteLike: "/delete/like/:comment_id",
        addDislike: "/add/dislike/:comment_id",
        deleteDislike: "/delete/dislike/:comment_id",
    },
    replyToComment: {
        baseUrl: "/reply-to-comment",
        getOneById: "/get/one/:reply_id",
        getRepliesByCommentId: "/get/all/:comment_id",
        createReply: "/create",
        editReply: "/edit",
        deleteReply: "/delete/:reply_id",
        reportReply: "/report/:type/:reply_id",
        addDislike: "/vote/add/dislike/:reply_id",
        addLike: "/vote/add/like/:reply_id",
        deleteDislike: "/vote/delete/dislike/:reply_id",
        deleteLike: "/vote/delete/like/:reply_id",
    },
    media: {
        baseUrl: "/media",
        setAvatar: "/avatar/set",
        updateAvatar: "/avatar/update",
        avatarViewByUsername: "/avatar/view-by-username/:username",
        deleteAvatar: "/avatar/delete",
        viewAvatarByFs: "/avatar/view-fs",
        UPLOAD_IMAGE_FILENAME: "one_image_file",
    },
    animeBookmarks: {
        baseUrl: "/anime/anime-bookmark-collection",
        getAllList: "/get/list/all",
        getForAnime: "/get-status-from-one/:anime_id",
        getListOfWatching: "/get/list/watching",
        getListOfAbandoned: "/get/list/abandoned",
        getListOfPlanned: "/get/list/planned",
        getListOfCompleted: "/get/list/completed",
        createWatching: "/add/watching/:anime_id",
        createAbandoned: "/add/abandoned/:anime_id",
        createPlanned: "/add/planned/:anime_id",
        createCompleted: "/add/completed/:anime_id",
        deleteWatching: "/delete/watching/:anime_id",
        deleteAbandoned: "/delete/abandoned/:anime_id",
        deletePlanned: "/delete/planned/:anime_id",
        deleteCompleted: "/delete/completed/:anime_id",
    },
    voteToAnime: {
        baseUrl: "/anime/vote-to-anime",
        exploreLikes: "/get/explore/likes",
        exploreDislikes: "/get/explore/dislikes",
        viewVoteOnAnime: "/get/view/vote/:anime_id",
        addLikeToAnime: "/add/like/:anime_id",
        deleteLikeFromAnime: "/delete/like/:anime_id",
        addDislikeToAnime: "/add/dislike/:anime_id",
        deleteDislikeFromAnime: "/delete/dislike/:anime_id",
    },
    ping: {
        baseUrl: "/ping",
        get: "/",
    },
} as const;
