import { apiKeyToServiceGuard } from "#/app/api-key.guard.js";
import { createConfiguredRouter } from "#/utilities/express-core-middlewares.js";
import { accountSectionRouter } from "#/app/user-account/user-account.route.js";
import { administratorSectionRouter } from "#/app/administrator/administrator.routes.js";
import { authenticationSectionRouter } from "#/app/authentication/authentication.route.js";
import { commentForAnimeSectionRouter } from "#/app/comment-for-anime/comment-for-anime.route.js";
import { voteToAnimeSectionRouter } from "#/app/vote-to-anime/vote-to-anime.route.js";
import { animeBookmarkSectionRouter } from "#/app/anime-bookmark-collection/anime-bookmark-collection.route.js";
import { pingSectionRouter } from "#/app/ping/ping.route.js";
import { profileSectionRouter } from "#/app/user-profile/user-profile.route.js";
import { replyToCommentSectionRouter } from "#/app/reply-to-comment/reply-to-comment.route.js";
import { secureHttpGuardMiddleware } from "./secure-http.guard.js";
import { mediaSectionRouter } from "#/app/media/media.route.js";
/** Entry Point Router */
export const appLayoutRouter = (() => {
    const router = createConfiguredRouter();
    router.use(apiKeyToServiceGuard);
    router.use(secureHttpGuardMiddleware);
    router.use("/authentication", authenticationSectionRouter);
    router.use("/administration", administratorSectionRouter);
    router.use("/comment-to-anime", commentForAnimeSectionRouter);
    router.use("/reply-to-comment", replyToCommentSectionRouter);
    router.use("/user-profile", profileSectionRouter);
    router.use("/media", mediaSectionRouter);
    router.use("/user-account", accountSectionRouter);
    router.use("/anime/anime-bookmark-collection", animeBookmarkSectionRouter);
    router.use("/vote-to-anime", voteToAnimeSectionRouter);
    router.use("/ping", pingSectionRouter);
    return router;
})();
